name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Security Audit
        run: npm audit --audit-level=high

      - name: Install Frontend Dependencies
        run: npm install

      - name: Build Website
        run: npm run build

      - name: Install Functions Dependencies
        run: cd functions && npm install

      - name: Build Functions
        run: cd functions && npm run build

      - name: Deploy to Firebase Hosting and Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_ID: integratedwellthsolutions
